#include "pqZeqManagerPanel.h"

// Qt includes
#include <QTreeWidget>
#include <QTreeWidgetItem>
#include <QVariant>
#include <QLabel>
#include <QComboBox>
#include <QTableWidget>
#include <QMessageBox>
#include <QProgressDialog>
#include <QTimer>
#include <QInputDialog>
#include <QFileDialog>
#include <QUrl>
#include <QDesktopServices>
#include <QThread>

// VTK includes

// ParaView Server Manager includes
#include "vtkSMInputProperty.h"
#include "vtkSMProxyManager.h"
#include "vtkSMSourceProxy.h"
#include "vtkSMStringVectorProperty.h"
#include "vtkSMIntVectorProperty.h"
#include "vtkSMArraySelectionDomain.h"
#include "vtkSMProxyProperty.h"
#include "vtkSMViewProxy.h"
#include "vtkSMRepresentationProxy.h"
#include "vtkSMPropertyHelper.h"
#include "vtkProcessModule.h"

// ParaView includes
#include "pqActiveObjects.h"
#include "pqApplicationCore.h"
#include "pqAutoGeneratedObjectPanel.h"
#include "pqSettings.h"
#include "pqOutputPort.h"
#include "pqPipelineSource.h"
#include "pqPropertyLinks.h"
#include "pqProxy.h"
#include "pqServer.h"
#include "pqServerManagerModelItem.h"
#include "pqServerManagerModel.h"
#include "pqSMAdaptor.h"
#include "pqTreeWidgetCheckHelper.h"
#include "pqTreeWidgetItemObject.h"
#include "pqTreeWidget.h"
#include "pqTreeWidgetItem.h"
#include "pqView.h"
#include "pqRenderView.h"
#include "pqDataRepresentation.h"
#include "pqDisplayPolicy.h"
#include "pqAnimationScene.h"
#include "pqPropertyManager.h"
#include "pqNamedWidgets.h"
//
#include "ui_pqZeqManagerPanel.h"
//----------------------------------------------------------------------------
//
//----------------------------------------------------------------------------
class pqZeqManagerPanel::pqUI : public QObject, public Ui::ZeqManagerPanel
{
public:
  pqUI(pqZeqManagerPanel* p) : QObject(p)
  {
    this->Links = new pqPropertyLinks;
  }
  //
  ~pqUI() {
    delete this->Links;
  }
  //
  pqPropertyLinks            *Links;
};
//----------------------------------------------------------------------------
//
//----------------------------------------------------------------------------
pqZeqManagerPanel::pqZeqManagerPanel(pqProxy* proxy, QWidget* p) :
  pqNamedObjectPanel(proxy, p) 
{
  this->UI = new pqUI(this);
  this->UI->setupUi(this);

  // inherited from pqNamedObjectPanel
  this->linkServerManagerProperties();
  
  this->connect(this->UI->refresh,
    SIGNAL(clicked()), this, SLOT(onRefresh()));

  //
  this->connect(this, SIGNAL(onaccept()), this, SLOT(onAccept()));

}
//----------------------------------------------------------------------------
pqZeqManagerPanel::~pqZeqManagerPanel()
{
}
//-----------------------------------------------------------------------------
void pqZeqManagerPanel::LoadSettings()
{
  pqSettings *settings = pqApplicationCore::instance()->settings();
  settings->beginGroup("ZeqManager");
  /*
  // InterpolationMethod
  this->UI->InterpolationMethod->setCurrentIndex(settings->value("InterpolationMethod", 0).toInt());
  // KernelType
  this->UI->KernelType->setCurrentIndex(settings->value("KernelType", 0).toInt());
  // KernelDimension
  this->UI->KernelDimension->setCurrentIndex(settings->value("KernelDimension", 0).toInt());
  // HCoefficient
  this->UI->HCoefficient->setText(settings->value("HCoefficient", 1.5).toString());
  // DefaultDensity
  this->UI->DefaultDensity->setText(settings->value("DefaultDensity", 1000.0).toString());
  // DefaultParticleSideLength
  this->UI->DefaultParticleSideLength->setText(settings->value("DefaultParticleSideLength", 0.18333).toString());
  // Max Neighbours
  this->UI->MaximumNeighbours->setText(settings->value("MaximumNeighbours", 64).toString()); 
  // MaxSearchRadius
  this->UI->MaximumSearchRadius->setText(settings->value("MaximumSearchRadius", 0.0).toString());
  */
  settings->endGroup();
}
//----------------------------------------------------------------------------
void pqZeqManagerPanel::SaveSettings()
{
  pqSettings *settings = pqApplicationCore::instance()->settings();
  settings->beginGroup("ZeqManager");
  /*
  // InterpolationMethod
  settings->setValue("InterpolationMethod", this->UI->InterpolationMethod->currentIndex());
  // KernelType
  settings->setValue("KernelType", this->UI->KernelType->currentIndex());
  // KernelDimension
  settings->setValue("KernelDimension", this->UI->KernelDimension->currentIndex());
  // HCoefficient
  settings->setValue("HCoefficient", this->UI->HCoefficient->text());
  // DefaultDensity
  settings->setValue("DefaultDensity", this->UI->DefaultDensity->text());
  // DefaultParticleSideLength
  settings->setValue("DefaultParticleSideLength", this->UI->DefaultParticleSideLength->text());
  // Max Neighbours
  settings->setValue("MaximumNeighbours", this->UI->MaximumNeighbours->text());
  // MaxSearchRadius
  settings->setValue("MaximumSearchRadius", this->UI->MaximumSearchRadius->text());
  */
  settings->endGroup();
}
//-----------------------------------------------------------------------------
void pqZeqManagerPanel::onAccept()
{
}
//-----------------------------------------------------------------------------
void pqZeqManagerPanel::onRefresh()
{
    this->referenceProxy()->getProxy()->InvokeCommand("Refresh");
}
//----------------------------------------------------------------------------

